# Generated by Django 2.2 on 2021-04-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_auto_20210428_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name_author',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
