# Generated by Django 2.2 on 2021-04-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0005_auto_20210428_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name_author',
            field=models.CharField(max_length=100, verbose_name='Имя пользователя'),
        ),
    ]
