# Generated by Django 2.2 on 2021-05-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0007_auto_20210501_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='news',
        ),
        migrations.AddField(
            model_name='comment',
            name='news_t',
            field=models.ManyToManyField(to='app_news.NewsItem'),
        ),
    ]
