# Generated by Django 2.2 on 2021-05-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0010_auto_20210501_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('news_items', models.ManyToManyField(to='app_news.NewsItem')),
            ],
        ),
    ]
