# Generated by Django 2.2 on 2021-05-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0011_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Издатель', 'verbose_name_plural': 'Издатели'},
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='publisher',
        ),
    ]
