# Generated by Django 2.2 on 2021-05-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0012_auto_20210501_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='was_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено администратором'),
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
