# Generated by Django 2.2 on 2021-05-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0013_auto_20210502_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='news',
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ManyToManyField(to='app_news.NewsItem'),
        ),
    ]
