# Generated by Django 2.2 on 2021-05-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0014_auto_20210503_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ManyToManyField(to='app_news.NewsItem', verbose_name='Новость'),
        ),
    ]
