# Generated by Django 2.2 on 2021-05-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0024_auto_20210527_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
