# Generated by Django 2.2 on 2021-05-27 06:58

import app_news.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0028_auto_20210527_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(app_news.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
