# Generated by Django 2.2 on 2021-05-27 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0035_auto_20210527_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(None), to=settings.AUTH_USER_MODEL),
        ),
    ]
